import { NextResponse } from "next/server";
import { handleUpload, type HandleUploadBody } from "@vercel/blob/client";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { handleApiError } from "@/lib/apiError";
import { ALLOWED_DOCUMENT_MIME_TYPES, MAX_FILE_SIZE_BYTES, DOCUMENTS_BLOB_TOKEN } from "@/lib/documentStorage";

// Same idea as app/api/uploads/property/route.ts, but for the supporting documents on a listing,
// which live in their own PRIVATE Vercel Blob store. The browser uploads the file straight to
// Blob (Vercel rejects request bodies over ~4.5MB on our own routes) using a short-lived token
// from here — locked to this listing's folder, to document file types, and to the size limit.
// The documents route afterwards just records the files that were uploaded.
export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
    }

    if (!DOCUMENTS_BLOB_TOKEN) {
      // Local dev without Blob: the form falls back to posting the files normally.
      return NextResponse.json({ error: "Blob storage is not configured.", blobConfigured: false }, { status: 501 });
    }

    const body = (await req.json()) as HandleUploadBody;

    const result = await handleUpload({
      token: DOCUMENTS_BLOB_TOKEN,
      request: req,
      body,
      onBeforeGenerateToken: async (pathname, clientPayload) => {
        const propertyId = clientPayload || "";
        const property = propertyId
          ? await prisma.property.findUnique({ where: { id: propertyId }, select: { sellerId: true } })
          : null;
        if (!property || property.sellerId !== session.user.id) {
          throw new Error("You can only upload documents for your own listings.");
        }
        if (!pathname.startsWith(`documents/${propertyId}/`)) {
          throw new Error("Invalid upload path.");
        }
        return {
          allowedContentTypes: ALLOWED_DOCUMENT_MIME_TYPES,
          maximumSizeInBytes: MAX_FILE_SIZE_BYTES,
          // The stored name is generated by the browser and recorded in the database as-is, so
          // the pathname must stay exactly what was requested.
          addRandomSuffix: false,
        };
      },
    });

    return NextResponse.json(result);
  } catch (err) {
    return handleApiError(err);
  }
}
