import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { handleApiError } from "@/lib/apiError";
import {
  DOCUMENT_TYPES,
  MAX_FILES_PER_UPLOAD,
  MAX_FILE_SIZE_BYTES,
  isAllowedFileType,
  randomStoredName,
  saveDocument,
  statDocument,
} from "@/lib/documentStorage";
import { recomputeDaktopVerified } from "@/lib/verificationStatus";

export async function POST(req: Request, { params }: { params: { id: string } }) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
    }

    const property = await prisma.property.findUnique({ where: { id: params.id } });
    if (!property) {
      return NextResponse.json({ error: "Property not found." }, { status: 404 });
    }

    if (property.sellerId !== session.user.id) {
      return NextResponse.json(
        { error: "You can only upload documents for your own listings." },
        { status: 403 }
      );
    }

    // JSON { documentType, uploaded: [...] } = files the browser already uploaded straight to the
    // private Blob store (avoids Vercel's ~4.5MB request limit); otherwise the old multipart form
    // (local dev fallback).
    if ((req.headers.get("content-type") || "").includes("application/json")) {
      const body = await req.json();
      const docType =
        typeof body?.documentType === "string" && DOCUMENT_TYPES.includes(body.documentType as any)
          ? body.documentType
          : null;
      const uploaded: Array<{ storedName?: unknown; fileName?: unknown }> = Array.isArray(body?.uploaded) ? body.uploaded : [];

      if (uploaded.length === 0) {
        return NextResponse.json({ error: "Choose at least one file to upload." }, { status: 400 });
      }
      if (uploaded.length > MAX_FILES_PER_UPLOAD) {
        return NextResponse.json(
          { error: `You can upload at most ${MAX_FILES_PER_UPLOAD} files at once.` },
          { status: 400 }
        );
      }

      const createdFromUpload = [];
      for (const item of uploaded) {
        const storedName = typeof item.storedName === "string" ? item.storedName : "";
        const fileName = (typeof item.fileName === "string" ? item.fileName.trim() : "").slice(0, 200) || "document";
        // Names are generated by the browser as "<uuid><.ext>"; anything else is not ours.
        if (!/^[0-9a-f-]{36}(\.[a-z0-9]{1,8})?$/i.test(storedName)) {
          return NextResponse.json({ error: "One of the uploaded files isn't valid. Please upload it again." }, { status: 400 });
        }

        // Trust what Blob actually holds, not what the client says about it.
        const stored = await statDocument(property.id, storedName);
        if (!stored) {
          return NextResponse.json({ error: `"${fileName}" didn't finish uploading. Please try again.` }, { status: 400 });
        }
        if (stored.size > MAX_FILE_SIZE_BYTES || !isAllowedFileType(stored.contentType.split(";")[0])) {
          return NextResponse.json(
            { error: `"${fileName}" is too large or not an allowed file type. Use PDF, JPG, PNG, WEBP, DOC, or DOCX under ${MAX_FILE_SIZE_BYTES / (1024 * 1024)}MB.` },
            { status: 400 }
          );
        }

        createdFromUpload.push(
          await prisma.propertyDocument.create({
            data: {
              propertyId: property.id,
              uploadedById: session.user.id,
              documentType: docType,
              fileName,
              storedName,
              mimeType: stored.contentType.split(";")[0] || null,
              fileSize: stored.size,
            },
          })
        );
      }

      await recomputeDaktopVerified(property.id);
      return NextResponse.json({ documents: createdFromUpload }, { status: 201 });
    }

    const formData = await req.formData();
    const files = formData.getAll("files").filter((f): f is File => f instanceof File);
    const documentTypeRaw = formData.get("documentType");
    const documentType =
      typeof documentTypeRaw === "string" && DOCUMENT_TYPES.includes(documentTypeRaw as any)
        ? documentTypeRaw
        : null;

    if (files.length === 0) {
      return NextResponse.json({ error: "Choose at least one file to upload." }, { status: 400 });
    }

    if (files.length > MAX_FILES_PER_UPLOAD) {
      return NextResponse.json(
        { error: `You can upload at most ${MAX_FILES_PER_UPLOAD} files at once.` },
        { status: 400 }
      );
    }

    for (const file of files) {
      if (file.size > MAX_FILE_SIZE_BYTES) {
        return NextResponse.json(
          { error: `"${file.name}" is too large. Max size is ${MAX_FILE_SIZE_BYTES / (1024 * 1024)}MB per file.` },
          { status: 400 }
        );
      }
      if (!isAllowedFileType(file.type)) {
        return NextResponse.json(
          { error: `"${file.name}" is not an allowed file type. Use PDF, JPG, PNG, WEBP, DOC, or DOCX.` },
          { status: 400 }
        );
      }
    }

    const created = [];
    for (const file of files) {
      const storedName = randomStoredName(file.name);
      await saveDocument(file, property.id, storedName);

      const doc = await prisma.propertyDocument.create({
        data: {
          propertyId: property.id,
          uploadedById: session.user.id,
          documentType,
          fileName: file.name,
          storedName,
          mimeType: file.type || null,
          fileSize: file.size,
        },
      });
      created.push(doc);
    }

    // A newly-uploaded document is unverified by definition, so a listing that was previously
    // fully verified loses the DAKTOP VERIFIED badge until this one is checked too.
    await recomputeDaktopVerified(property.id);

    return NextResponse.json({ documents: created }, { status: 201 });
  } catch (err) {
    return handleApiError(err);
  }
}
